version: "3"

services:
  db:
    image: mariadb:10
    ports:
      - 3307:3306
      # - 3309:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      # - ./db/data:/var/lib/mysql
      # - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env.local
    # env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always