services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: base:latest
  nestjs:
    depends_on:
      - base
    restart: always
    # image: base:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DOMAIN=http://host.docker.internal
      - CORS_ORIGIN_LIST=http://host.docker.internal:3001
    env_file:
      - ./server/.env
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app/server
    # entrypoint: /app/server/entrypoint.sh
  client:
    depends_on:
      - base
    restart: always
    # image: base:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app/client
    # entrypoint: /app/client/entrypoint.sh